name: env_modelos_fisio
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - _r-mutex=1.0.1
  - anyio=4.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2025.8.3
  - cffi=1.17.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.10.18
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.16.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - icc_rt=2022.1.0
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - khronos-opencl-icd-loader=2024.05.08
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=3.0
  - libblas=3.9.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libsodium=1.0.20
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxgboost=2.1.3
  - libzlib=1.3.1
  - llvmlite=0.44.0
  - lz4-c=1.9.4
  - m2w64-bwidget=1.9.10
  - m2w64-bzip2=1.0.6
  - m2w64-expat=2.1.1
  - m2w64-fftw=3.3.4
  - m2w64-flac=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-gsl=2.1
  - m2w64-libiconv=1.14
  - m2w64-libjpeg-turbo=1.4.2
  - m2w64-libogg=1.3.2
  - m2w64-libpng=1.6.21
  - m2w64-libsndfile=1.0.26
  - m2w64-libtiff=4.0.6
  - m2w64-libvorbis=1.3.5
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-libxml2=2.9.3
  - m2w64-mpfr=3.1.4
  - m2w64-pcre2=10.34
  - m2w64-speex=1.2rc2
  - m2w64-speexdsp=1.2rc3
  - m2w64-tcl=8.6.5
  - m2w64-tk=8.6.5
  - m2w64-tktable=2.10
  - m2w64-wineditline=2.101
  - m2w64-xz=5.2.2
  - m2w64-zlib=1.2.8
  - markupsafe=3.0.2
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numexpr=2.11.0
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.5.3
  - overrides=7.4.0
  - packaging=25.0
  - pandas=2.3.2
  - pandoc=2.12
  - pandocfilters=1.5.1
  - parso=0.8.5
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.4.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.3
  - pycparser=2.23
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - r-base=4.1.3
  - referencing=0.30.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - rpy2=3.5.11
  - scikit-learn=1.7.1
  - scipy=1.15.3
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=78.1.1
  - shap=0.48.0
  - simplegeneric=0.8.1
  - six=1.17.0
  - slicer=0.0.8
  - soupsieve=2.5
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2021.8.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - tzlocal=5.3.1
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xgboost=2.1.3
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - attrs==25.3.0
      - charset-normalizer==3.4.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - filelock==3.19.1
      - fonttools==4.59.2
      - fsspec==2025.9.0
      - idna==3.10
      - kiwisolver==1.4.9
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - outcome==1.3.0.post0
      - pillow==11.3.0
      - polars==1.33.1
      - pyparsing==3.2.3
      - python-dotenv==1.1.1
      - selenium==4.35.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sympy==1.13.1
      - torch==2.8.0
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - trio==0.30.0
      - trio-websocket==0.12.2
      - typing-extensions==4.14.1
      - ultralytics==8.3.198
      - ultralytics-thop==2.0.17
      - webdriver-manager==4.0.2
      - wsproto==1.2.0
